// References
#pragma region
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <stdbool.h>
#include <string.h>
#include <locale.h>
#include "ChessUtilities.h"

// Compile and Execute:
// clear && gcc InMediaChess.c ChessUtilities.c -o InMediaChess.out && ./InMediaChess.out

bool MainMenu(bool* debug);
void PrintGreeting(void);    
void GenerateBoard(bool debug);
void PrintBoard(char* board[8][8]);
void PrintLine(void);
void InitializeBoard(char* board[8][8]);
void PrintGameRules(bool debug);
void InputErrorMessage(void);

#pragma endregion

// Main and Ultilities
#pragma region
int main(void)
{
    bool debug = false;

    while(MainMenu(&debug))
    {

    }

    return 0;
}

bool MainMenu(bool* debug)
{
    setlocale(LC_ALL, "");

    PrintGreeting();

    srand(time(NULL));

    int input = -1;
    
    if(!scanf("%d", &input))
    {
        InputErrorMessage();
        return false;
    }
    
    switch(input)
    {
        // Prints game rules
        case 2:
        PrintGameRules(*debug);
        
        char YN = 'N';

        while(true)
        {
            puts("Would you like to try the game out now? [Y/N]");

            if(!scanf(" %c", &YN))
            {
                InputErrorMessage();
                return false;
            }
            
            printf("\n");

            switch(YN)
            {
                case 'Y':
                case 'y':
                break;

                case 'N':
                case 'n':
                puts("Understood, have a good day!\n");
                puts("Exiting...\n");
                return false;

                default:
                puts("Sorry, I didn't understand. Be sure to answer either Y for Yes ot N for no.\n");
                continue;
            }
            break;
        }


        // Generates the board
        case 1:
        GenerateBoard(*debug);
        
        // Exits the program via user input
        case 3:
        printf("Exiting...\n\n");
        return false;
        

        case -1969667086:
        if(*debug)
        {
            puts("\n\tDEBUG MODE => OFF\n");
            *debug = false;
        }
        else 
        {
            puts("\nDEBUG MODE => ON\n");
            *debug = true;
        }  
        return true;

        // Exits the program via input error
        default:
        printf("ERROR: INPUT %d COULD NOT BE INTERPRETED, WILL EXIT PROGRAM NOW\n\n", input);
        return false;
    }
}

void PrintGreeting(void)
{
    puts("Hello!\n");
    puts("Welcome to \"In Media Chess,\" a proceedurally random board generator for more interesting chess games!\n");
    puts("Please select one of the options below:");
    puts("1: Generate Board");
    puts("2: Variation Rules");
    puts("3: Exit Program");
    printf("\n");
}

void PrintLine(void)
{
    puts("  -------------------");
}

void PrintGameRules(bool debug)
{
    printf(
        "\n"
        "---Information---\n"
        "\n"
        "This is In Media Chess, a chess variant that keeps all the rules of chess the same except for a few simple changes.\n"
        "\tThank you for trying out In Media Chess! It really means a lot to me that you've shown interest in this pet project of mine!\n"
        "\n"
        "This program was coded entirely in C, and took about a month of on-and-off labor to put together.\n"
        "\tWhile I don't think it's perfect, I am happy with its current state.\n"
        "\n"
        "Version: V1.1\n"
        "\n"
        "---Setup---\n"
        "\n"
        "First, decide by any means who will be Player 1 (P1) and who will be Player 2 (P2).\n"
        "\tP1 will play White and P2 will play Black; White goes first.\n"
        "\n"
        "---Procedural Generation---\n"
        "\n"
        "When you select to generate a board, a board-state will be procedurally generated.\n"
        "\tThe purpose is to minimize the usefulness of memorizing chess openings, focusing on raw strategy instead.\n"
        "\tIn practice, the board-state is meant to joining a chess game after an unknown number of turns has passed.\n"
        "\tThat is, the board-states generated by this program should be possible through normal gameplay.\n"
        "\n"
        "White and black pieces are generated in pairs.\n"
        "\tWhite and Black will have the same amount and types of pieces.\n"
        "\tThe positions of a White piece and its corresponding Black piece will be rotationally symmetric about the center of the board.\n"
        "\tIf a White piece is captured during generation, it's corresponding Black piece is captured too.\n"
        "\tSimilarly, if a White Pawn promotes, so does its corresponding Black Pawn.\n"
        "\n"
        "Altogether, this helps ensure the board-state is as fair as possible.\n"
        "\n"
        "---Basics---\n"
        "\n"
        "All pieces move like they would in a normal game of chess.\n"
        "\tFor clarity, %s  move %s, while %s  move %s.\n"
        "\n"
        "The object of the game is still to checkmate your opponent's king.\n"
        "\tThis means placing the opponent's king in an inescapable threat of capture.\n"
        "\n"
        "Due to the nature of this variation, castling, and en passant are not allowed.\n"
        "\tEven assuming a king and rook generated on their standard starting positions (very unlikely),\n"
        "\t\tit would be impossible to know if either moved away and then moved back to their standard starting position or not.\n"
        "\tIt would also be impossible to know if a pawn moved two spaces in two turns, or two spaces in one turn.\n"
        "\n"
        "---Stalemate rules---\n"
        "\n"
        "The game ends in stalemate when one or both of the following happen:\n"
        "\t20 consecutive turns with no captures or pawn movements\n"
        "\tThe turn player is not in check, but has no valid moves\n"
        "\n"
        "---Role Reversal---\n"
        "\n"
        "Further, due to the nature of this variant, it is possible for the game to begin in a \'Mate in One\' scenario.\n"
        "\tThis results in P2 can losing before their first turn with no counterplay.\n"
        "\n"
        "To remedy this, I introduce the most significant change with this variation: Role Reversal!\n"
        "\tP2 gets the option to swap roles with P1 as their first turn, after which their turn ends:\n"
        "\tP1 => Black; P2 => White; it is now P1's turn again\n"
        "\n"
        "P1 does not get this option at all, and P2 cannot do this once their first turn is over.\n"
        "\n"
        "A Role Reversal counts as a valid action, and thus can be used by P2 to avoid checkmate on their first turn.\n"
        "\tSpecifically, if P1 manages to \'Mate in One\' P2 on P1's first turn, P2 can do a Role Reversal.\n"
        "\tThis leads to P1 becoming Black, and P2 becoming White, allowing P2 to use P1's own \'Mate in One\' against them.\n"
        "\n"
        "While a key use of Role Reversal is to avoid a first-turn checkmate, P2 can do a Role Reversal for any other reason too.\n"
        "\tOverall, this helps guarantee P2 has at least 1 turn to avoid checkmate despite the procedurally generated board state.\n"
        "\nIt otherwise helps mitigate P1's first-turn advantage.\n"
        "\n"
        "Reference:\n"
        "      P R N B Q K\n"
        "White %s %s %s %s %s %s\n"
        "Black %s %s %s %s %s %s\n"
        "\n",
        ChessPiece("WP"), "\u2191",
        ChessPiece("BP"), "\u2193",
        ChessPiece("WP"), ChessPiece("WR"), 
        ChessPiece("WN"), ChessPiece("WB"),
        ChessPiece("WQ"), ChessPiece("WK"), 
        ChessPiece("BP"), ChessPiece("BR"),
        ChessPiece("BN"), ChessPiece("BB"),
        ChessPiece("BQ"), ChessPiece("BK")
    );
    debug ? puts("WARNING: DEBUG MODE IS ACTIVE\n") : (void)0;
}

void GenerateBoard(bool debug)
{
    char* board[8][8];
    int bonusIterations[4] = {0, 0, 0, 0};
    InitializeBoard(board);
    
    /*
    Generation notes:
    1. No more than 16 pieces for each player
    2. No more than 8 pawns
    3. Pawn has 20% chance, each, to not exist, 5% chance to be promoted to a different piece
    4. All other pieces (except King) have a 10% chance to not exist
    */
    
    // Place Pawns (8 ct, not on first or final row)
    debug ? puts("\nGenerating Pawns:") : printf("Generating");
    PlacePawns(board, bonusIterations, debug);
    if(debug) 
    {
        puts("\tDone.\n");
        PrintBoard(board);
    }
    else
        printf(".");
    
    // Note: Bonus iterations are in order as listed here

    // Place Rooks (2 ct, place anywhere)
    debug ? puts("Generating Rooks:") : (void)0;
    PlaceRooks(board, bonusIterations[0], debug);
    if(debug) 
    {
        puts("\tDone.\n");
        PrintBoard(board);
    }
    else
        printf(".");

    // Place Bishops (2ct: one on Dark Square, one on Light square)
    debug ? puts("Generating Bishops:") : (void)0;
    PlaceBishops(board, bonusIterations[1], debug);
    if(debug) 
    {
        puts("\tDone.\n");
        PrintBoard(board);
    }
    else
        printf(".");

    // Place Knights (2 ct, place anywhere)
    debug ? puts("Generating Knights:") : (void)0;
    PlaceKnights(board, bonusIterations[2], debug);
    if(debug)
    {
        puts("\tDone.\n");
        PrintBoard(board);
    }
    else
        printf(".");

    // Place Queens (1 ct, anywhere)
    debug ? puts("Generating Queens:") : (void)0;
    PlaceQueens(board, bonusIterations[3], debug);
    if(debug) 
    {
        puts("\tDone.\n");
        PrintBoard(board);
    }
    else
        printf(".");

    // Place Kings (1 ct, re-run if check)
    debug ? puts("Generating Kings:\n") : (void)0;
    PlaceKing(board, debug);
    debug ? puts("\nBoard generation complete, printing board:\n") : puts("\nDone.\n");

    PrintBoard(board);
}

void InitializeBoard(char* board[8][8])
{
    for(int i = 0; i < 8; i++)
    {
        for(int j = 0; j < 8; j++)
        {
            if((i + j) % 2 == 0)
            {
                board[i][j] = ChessPiece("WS");

            }
            else
            {
                board[i][j] = ChessPiece("BS");

            }
            
        }
    }
}

void PrintBoard(char* board[8][8])
{
    puts("    A B C D E F G H");
    
    PrintLine();

    for(int i = 0; i < 8; i++)
    {
        // Prints row header
        printf("%d | ", 8 - i);
        
        for(int j = 0; j < 8; j++)
        {
            printf("%s ", board[i][j]);
        }

        printf("|\n");

    }

    PrintLine();

    printf("\n");
}

void InputErrorMessage(void)
{
    puts("ERROR: Unable to read user input!");
}

#pragma endregion